[libraries]

lib.files = [
"proj/test/tb_shifter_N.vhd",
"proj/test/tb_control_unit.vhd",
"proj/test/tb_alu.vhd",
"proj/test/half_adder_tb.vhd",
"proj/test/half_adder_N_tb.vhd",
"proj/src/MIPS_types.vhd",
"internal/testpy/tb.vhd",
"internal/boilerplate_src/MIPS_types.vhd",
"proj/src/TopLevel/mips.vhd",
"proj/src/TopLevel/mem.vhd",
"proj/src/TopLevel/MIPS_Processor.vhd",
"internal/boilerplate_src/TopLevel/mem.vhd",
"internal/boilerplate_src/TopLevel/MIPS_Processor.vhd",
"proj/src/TopLevel/low_level/xorg32.vhd",
"proj/src/TopLevel/low_level/xorg2.vhd",
"proj/src/TopLevel/low_level/org32.vhd",
"proj/src/TopLevel/low_level/org2.vhd",
"proj/src/TopLevel/low_level/norg32.vhd",
"proj/src/TopLevel/low_level/nandg32.vhd",
"proj/src/TopLevel/low_level/mux32t1.vhd",
"proj/src/TopLevel/low_level/mux2t1_N.vhd",
"proj/src/TopLevel/low_level/mux2t1.vhd",
"proj/src/TopLevel/low_level/mux16t1.vhd",
"proj/src/TopLevel/low_level/invg.vhd",
"proj/src/TopLevel/low_level/fullAdder.vhd",
"proj/src/TopLevel/low_level/extender16t32.vhd",
"proj/src/TopLevel/low_level/dffg_tb.vhd",
"proj/src/TopLevel/low_level/dffg_n.vhd",
"proj/src/TopLevel/low_level/dffg.vhd",
"proj/src/TopLevel/low_level/decoder5t32.vhd",
"proj/src/TopLevel/low_level/andg32.vhd",
"proj/src/TopLevel/low_level/andg2.vhd",
"proj/src/TopLevel/fetch/register_file.vhd",
"proj/src/TopLevel/fetch/nbitregister.vhd",
"proj/src/TopLevel/fetch/half_adder_N.vhd",
"proj/src/TopLevel/fetch/half_adder.vhd",
"proj/src/TopLevel/fetch/fetch_unit.vhd",
"proj/src/TopLevel/fetch/MIPS_pc_dffg.vhd",
"proj/src/TopLevel/fetch/MIPS_pc.vhd",
"proj/src/TopLevel/control_unit/control.vhd",
"proj/src/TopLevel/barrel_shifter/shifter_N.vhd",
"proj/src/TopLevel/alu/ripple_carry_adder_N.vhd",
"proj/src/TopLevel/alu/comp1_N.vhd",
"proj/src/TopLevel/alu/alu.vhd",
"proj/src/TopLevel/alu/adder_subtractor.vhd",
]
